### ISSUE TITLE
Both .yml and .yaml extensions are used with manifest files

### ISSUE THREAD

**Issue by summis** [kubernetes-hy/kubernetes-hy.github.io#4]
Currently these both extensions are used in material while it would be more consistent to use just one. Maybe .yaml would be correct : https://stackoverflow.com/a/22268973

**Comment by Jakousa** [comment]
yaml is the correct one. Let's use that for the whole course.

Kubernetes documentation uses yaml everywhere. Github has examples using yml and so does docker-compose - both support yaml.

Fixed in https://github.com/kubernetes-hy/kubernetes-hy.github.io/commit/b33786617c91680129b609d4f333c297fb8f3aaf
